clear;clc;close all;

listof = {...
    'pieces_B4_mono', ...
    'pieces_B7_mono', ...
    'pieces_B10_mono', ...
    'pieces_A4_mono', ...
    'pieces_A7_mono', ...
    'pieces_A10_mono', ...
    'pieces_no_root_B4_mono', ...
    'pieces_no_root_B7_mono', ...
    'pieces_no_root_B10_mono', ...
    'pieces_no_root_A4_mono', ...
    'pieces_no_root_A7_mono', ...
    'pieces_no_root_A10_mono', ...
    'pieces_A10PB4N', ...
    'pieces_A10PB7N', ...
    'pieces_A10PB10N', ...
    'pieces_no_root_A10PB4N', ...
    'pieces_no_root_A10PB7N', ...
    'pieces_no_root_A10PB10N', ...
    };

for a = 1:length(listof)
    assemble_voltages(listof{a});
end