function [V_extra, domain, spl, n_nodes,diam] = get_spline_voltages(fem,datadir,inl,ppn)
%get_line_voltages.m Generate text file list of voltage values for NEURON communication
% fem is the comsol model object
% N is the number of diameters to simulate

geom = 'geom1';

pts = csvread([datadir 'root_centers_um.csv']);
pts = pts';

spl_func = cscvn(pts(:,1:end));

% how many times longer is a paranode than a node?
%diam = log(random('logn', 9, 0.2, 1, 1));
diam = 9;
fib_len = arclength(pts(1,:),pts(2,:),pts(3,:),'spline');
n_nodes = floor((fib_len)./(diam*(inl+1)));
% how many nodes and paranodes does the axon have.

s = linspace(spl_func.breaks(1),spl_func.breaks(end),ppn*n_nodes);
spl = fnval(spl_func,s);

if 0 
figure
hold on
fnplt(spl_func,'r',2)
get_geom_names;

%% View Geometry
nice_colors = parula(21);
ax = gca;

% Plot neuron
% [tree, name, path] = load_tree([tempdata_address 'model_tree.neu']);
% plot_tree(tree{1},[1 0 0]);
% hold on;
% plot_tree(tree{2},[1 0 0]);


%edges
mphviewselection(fem,geom,el_edge, ...
    'entity', 'edge', ...
    'parent',ax, ...
    'facealpha', 0, ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', [0 0 0], ...
    'edgecolor', [0 0 0] ...
    );

%faces
mphviewselection(fem,geom,el_dom, ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 1, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(1,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );

% Plot GM

%edges
mphviewselection(fem,geom,gm_edge, ...
    'entity', 'edge', ...
    'parent',ax, ...
    'facemode', 'off', ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', [0 0 0], ...
    'edgecolor', [0 0 0] ...
    );

%faces
mphviewselection(fem,geom,gm_dom(1:6), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.4, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(1,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
%faces
mphviewselection(fem,geom,gm_dom(7:end), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.4, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(1,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );

% Plot WM

%edges
mphviewselection(fem,geom,wm_edge, ...
    'entity', 'edge', ...
    'parent',ax, ...
    'facemode', 'off', ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', [0 0 0], ...
    'edgecolor', [0 0 0] ...
    );

%faces
mphviewselection(fem,geom,wm_dom(1:6), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.2, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(5,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
%faces
mphviewselection(fem,geom,wm_dom(7:end), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.4, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(5,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );


%edges
mphviewselection(fem,geom,csf_edge, ...
    'entity', 'edge', ...
    'parent',ax, ...
    'facemode', 'off', ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', [0 0 0], ...
    'edgecolor', [0 0 0] ...
    );

%faces
mphviewselection(fem,geom,csf_dom(1:6), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.1, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(10,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
%faces
mphviewselection(fem,geom,csf_dom(7:end), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.4, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(10,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
%axis([-4000 4000 -4000 4000 -4000 10000]);
%view([0,0]);
xlabel('x (um)');
ylabel('y (um)');
zlabel('z (um)');
print('-dpng',[datadir 'axon_view']);
end
V_extra=mphinterp(fem,'V','coord',spl);
% interpolate voltages from the COMSOL solution
domain = mphinterp(fem,'dom','coord',spl);

end
