%clear;clc;
close all;
comsol_file = 'Z:\Spinal Cord Model\COMSOL\roots_of_passage\just_cord';
%comsol_file = 'A:\CSN - Corticospinal Neuroprosthetics\CSP Model\Spinal cord models\No root\no_root_HiRes';
%fem = mphload([comsol_file '.mph']);
geom = 'geom1';

system_id_old;
get_geom_names;
nice_colors = parula(21);
rfig();
hold on;
[tree, name, path] = load_tree([tempdata_address 'model_tree.neu']);
ax = gca;

%edges
mphviewselection(fem,geom,el_edge, ...
    'entity', 'edge', ...
    'parent',ax, ...
    'facealpha', 0, ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', [0 0 0], ...
    'edgecolor', [0 0 0] ...
    );

%faces
mphviewselection(fem,geom,el_dom, ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 1, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(1,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );

% Plot GM
% 
% %edges
% mphviewselection(fem,geom,gm_edge, ...
%     'entity', 'edge', ...
%     'parent',ax, ...
%     'facemode', 'off', ...
%     'geommode', 'off', ...
%     'edgemode', 'on', ...
%     'edgecolorselected', [0 0 0], ...
%     'edgecolor', [0 0 0] ...
%     );

%faces
mphviewselection(fem,geom,gm_dom(1:6), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.1, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(1,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
%faces
mphviewselection(fem,geom,gm_dom(7:end), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.2, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(1,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );

% Plot WM
% 
% %edges
% mphviewselection(fem,geom,wm_edge, ...
%     'entity', 'edge', ...
%     'parent',ax, ...
%     'facemode', 'off', ...
%     'geommode', 'off', ...
%     'edgemode', 'on', ...
%     'edgecolorselected', [0 0 0], ...
%     'edgecolor', [0 0 0] ...
%     );

%faces
mphviewselection(fem,geom,wm_dom(1:6), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.1, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(5,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
%faces
mphviewselection(fem,geom,wm_dom(7:end), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.2, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(5,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );

% CSF

% %edges
% mphviewselection(fem,geom,csf_edge, ...
%     'entity', 'edge', ...
%     'parent',ax, ...
%     'facemode', 'off', ...
%     'geommode', 'off', ...
%     'edgemode', 'on', ...
%     'edgecolorselected', [0 0 0], ...
%     'edgecolor', [0 0 0] ...
%     );

%faces
mphviewselection(fem,geom,csf_dom(1:6), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.1, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(10,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
%faces
mphviewselection(fem,geom,csf_dom(7:end), ...
    'entity', 'domain', ...
    'parent',ax, ...
    'facealpha', 0.2, ...
    'facecolor', [1 0 0], ...
    'facecolorselected', nice_colors(10,:), ...
    'geommode', 'off', ...
    'edgemode', 'on', ...
    'edgecolorselected', 'k', ...
    'edgecolor', 'k' ...
    );
options = {['']};
plot_tree(tree{1},[1 0 0],[],[],[],'-b -extrathick');
plot_tree(tree{2},[1 0 0],[],[],[],'-b -extrathick');

view(2);
campos([5e6 -5e6 -50e6]);
camtarget([0e6 0e6 10e6]);
camroll(-45);
zoom(1.2);
title('Axon View');
xlabel('x (mm)');
ylabel('y (mm)');
zlabel('z (mm)');
print('-dpng',[tempdata_address 'axon_view']);

