# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mujoco2py.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mujoco2py.proto',
  package='mujoco2py',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmujoco2py.proto\x12\tmujoco2py\"\xb7\x03\n\nmujoco_msg\x12-\n\x05joint\x18\x01 \x03(\x0b\x32\x1e.mujoco2py.mujoco_msg.mj_joint\x12)\n\x03\x61\x63t\x18\x02 \x03(\x0b\x32\x1c.mujoco2py.mujoco_msg.mj_act\x12+\n\x04tend\x18\x03 \x03(\x0b\x32\x1d.mujoco2py.mujoco_msg.mj_tend\x12+\n\x04site\x18\x04 \x03(\x0b\x32\x1d.mujoco2py.mujoco_msg.mj_site\x1a\x35\n\x08mj_joint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04qpos\x18\x02 \x01(\x01\x12\r\n\x05\x66orce\x18\x03 \x01(\x01\x1a\x33\n\x06mj_act\x12\x0c\n\x04\x63trl\x18\x01 \x01(\x01\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x66orce\x18\x03 \x01(\x01\x1aO\n\x07mj_tend\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03len\x18\x02 \x01(\x01\x12\x0c\n\x04len0\x18\x03 \x01(\x01\x12\x0f\n\x07len_dot\x18\x04 \x01(\x01\x12\n\n\x02ma\x18\x05 \x01(\x01\x1a\x38\n\x07mj_site\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\"1\n\x0bgeneral_msg\x12\x13\n\x0binstruction\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MUJOCO_MSG_MJ_JOINT = _descriptor.Descriptor(
  name='mj_joint',
  full_name='mujoco2py.mujoco_msg.mj_joint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mujoco2py.mujoco_msg.mj_joint.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qpos', full_name='mujoco2py.mujoco_msg.mj_joint.qpos', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='force', full_name='mujoco2py.mujoco_msg.mj_joint.force', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=278,
)

_MUJOCO_MSG_MJ_ACT = _descriptor.Descriptor(
  name='mj_act',
  full_name='mujoco2py.mujoco_msg.mj_act',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctrl', full_name='mujoco2py.mujoco_msg.mj_act.ctrl', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='mujoco2py.mujoco_msg.mj_act.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='force', full_name='mujoco2py.mujoco_msg.mj_act.force', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=331,
)

_MUJOCO_MSG_MJ_TEND = _descriptor.Descriptor(
  name='mj_tend',
  full_name='mujoco2py.mujoco_msg.mj_tend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mujoco2py.mujoco_msg.mj_tend.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='len', full_name='mujoco2py.mujoco_msg.mj_tend.len', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='len0', full_name='mujoco2py.mujoco_msg.mj_tend.len0', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='len_dot', full_name='mujoco2py.mujoco_msg.mj_tend.len_dot', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ma', full_name='mujoco2py.mujoco_msg.mj_tend.ma', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=412,
)

_MUJOCO_MSG_MJ_SITE = _descriptor.Descriptor(
  name='mj_site',
  full_name='mujoco2py.mujoco_msg.mj_site',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mujoco2py.mujoco_msg.mj_site.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='mujoco2py.mujoco_msg.mj_site.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='mujoco2py.mujoco_msg.mj_site.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='mujoco2py.mujoco_msg.mj_site.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=470,
)

_MUJOCO_MSG = _descriptor.Descriptor(
  name='mujoco_msg',
  full_name='mujoco2py.mujoco_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joint', full_name='mujoco2py.mujoco_msg.joint', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='act', full_name='mujoco2py.mujoco_msg.act', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tend', full_name='mujoco2py.mujoco_msg.tend', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='site', full_name='mujoco2py.mujoco_msg.site', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MUJOCO_MSG_MJ_JOINT, _MUJOCO_MSG_MJ_ACT, _MUJOCO_MSG_MJ_TEND, _MUJOCO_MSG_MJ_SITE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=470,
)


_GENERAL_MSG = _descriptor.Descriptor(
  name='general_msg',
  full_name='mujoco2py.general_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instruction', full_name='mujoco2py.general_msg.instruction', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mujoco2py.general_msg.value', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=521,
)

_MUJOCO_MSG_MJ_JOINT.containing_type = _MUJOCO_MSG
_MUJOCO_MSG_MJ_ACT.containing_type = _MUJOCO_MSG
_MUJOCO_MSG_MJ_TEND.containing_type = _MUJOCO_MSG
_MUJOCO_MSG_MJ_SITE.containing_type = _MUJOCO_MSG
_MUJOCO_MSG.fields_by_name['joint'].message_type = _MUJOCO_MSG_MJ_JOINT
_MUJOCO_MSG.fields_by_name['act'].message_type = _MUJOCO_MSG_MJ_ACT
_MUJOCO_MSG.fields_by_name['tend'].message_type = _MUJOCO_MSG_MJ_TEND
_MUJOCO_MSG.fields_by_name['site'].message_type = _MUJOCO_MSG_MJ_SITE
DESCRIPTOR.message_types_by_name['mujoco_msg'] = _MUJOCO_MSG
DESCRIPTOR.message_types_by_name['general_msg'] = _GENERAL_MSG

mujoco_msg = _reflection.GeneratedProtocolMessageType('mujoco_msg', (_message.Message,), dict(

  mj_joint = _reflection.GeneratedProtocolMessageType('mj_joint', (_message.Message,), dict(
    DESCRIPTOR = _MUJOCO_MSG_MJ_JOINT,
    __module__ = 'mujoco2py_pb2'
    # @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_joint)
    ))
  ,

  mj_act = _reflection.GeneratedProtocolMessageType('mj_act', (_message.Message,), dict(
    DESCRIPTOR = _MUJOCO_MSG_MJ_ACT,
    __module__ = 'mujoco2py_pb2'
    # @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_act)
    ))
  ,

  mj_tend = _reflection.GeneratedProtocolMessageType('mj_tend', (_message.Message,), dict(
    DESCRIPTOR = _MUJOCO_MSG_MJ_TEND,
    __module__ = 'mujoco2py_pb2'
    # @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_tend)
    ))
  ,

  mj_site = _reflection.GeneratedProtocolMessageType('mj_site', (_message.Message,), dict(
    DESCRIPTOR = _MUJOCO_MSG_MJ_SITE,
    __module__ = 'mujoco2py_pb2'
    # @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_site)
    ))
  ,
  DESCRIPTOR = _MUJOCO_MSG,
  __module__ = 'mujoco2py_pb2'
  # @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg)
  ))
_sym_db.RegisterMessage(mujoco_msg)
_sym_db.RegisterMessage(mujoco_msg.mj_joint)
_sym_db.RegisterMessage(mujoco_msg.mj_act)
_sym_db.RegisterMessage(mujoco_msg.mj_tend)
_sym_db.RegisterMessage(mujoco_msg.mj_site)

general_msg = _reflection.GeneratedProtocolMessageType('general_msg', (_message.Message,), dict(
  DESCRIPTOR = _GENERAL_MSG,
  __module__ = 'mujoco2py_pb2'
  # @@protoc_insertion_point(class_scope:mujoco2py.general_msg)
  ))
_sym_db.RegisterMessage(general_msg)


# @@protoc_insertion_point(module_scope)
