// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mujoco2py.proto

#ifndef PROTOBUF_mujoco2py_2eproto__INCLUDED
#define PROTOBUF_mujoco2py_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mujoco2py {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_mujoco2py_2eproto();
void protobuf_AssignDesc_mujoco2py_2eproto();
void protobuf_ShutdownFile_mujoco2py_2eproto();

class general_msg;
class mujoco_msg;
class mujoco_msg_mj_act;
class mujoco_msg_mj_joint;
class mujoco_msg_mj_site;
class mujoco_msg_mj_tend;

// ===================================================================

class mujoco_msg_mj_joint : public ::google::protobuf::Message {
 public:
  mujoco_msg_mj_joint();
  virtual ~mujoco_msg_mj_joint();

  mujoco_msg_mj_joint(const mujoco_msg_mj_joint& from);

  inline mujoco_msg_mj_joint& operator=(const mujoco_msg_mj_joint& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const mujoco_msg_mj_joint& default_instance();

  void Swap(mujoco_msg_mj_joint* other);

  // implements Message ----------------------------------------------

  inline mujoco_msg_mj_joint* New() const { return New(NULL); }

  mujoco_msg_mj_joint* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mujoco_msg_mj_joint& from);
  void MergeFrom(const mujoco_msg_mj_joint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(mujoco_msg_mj_joint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional double qpos = 2;
  void clear_qpos();
  static const int kQposFieldNumber = 2;
  double qpos() const;
  void set_qpos(double value);

  // optional double force = 3;
  void clear_force();
  static const int kForceFieldNumber = 3;
  double force() const;
  void set_force(double value);

  // @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_joint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  double qpos_;
  double force_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_mujoco2py_2eproto();
  friend void protobuf_AssignDesc_mujoco2py_2eproto();
  friend void protobuf_ShutdownFile_mujoco2py_2eproto();

  void InitAsDefaultInstance();
  static mujoco_msg_mj_joint* default_instance_;
};
// -------------------------------------------------------------------

class mujoco_msg_mj_act : public ::google::protobuf::Message {
 public:
  mujoco_msg_mj_act();
  virtual ~mujoco_msg_mj_act();

  mujoco_msg_mj_act(const mujoco_msg_mj_act& from);

  inline mujoco_msg_mj_act& operator=(const mujoco_msg_mj_act& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const mujoco_msg_mj_act& default_instance();

  void Swap(mujoco_msg_mj_act* other);

  // implements Message ----------------------------------------------

  inline mujoco_msg_mj_act* New() const { return New(NULL); }

  mujoco_msg_mj_act* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mujoco_msg_mj_act& from);
  void MergeFrom(const mujoco_msg_mj_act& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(mujoco_msg_mj_act* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double ctrl = 1;
  void clear_ctrl();
  static const int kCtrlFieldNumber = 1;
  double ctrl() const;
  void set_ctrl(double value);

  // optional string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional double force = 3;
  void clear_force();
  static const int kForceFieldNumber = 3;
  double force() const;
  void set_force(double value);

  // @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_act)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double ctrl_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  double force_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_mujoco2py_2eproto();
  friend void protobuf_AssignDesc_mujoco2py_2eproto();
  friend void protobuf_ShutdownFile_mujoco2py_2eproto();

  void InitAsDefaultInstance();
  static mujoco_msg_mj_act* default_instance_;
};
// -------------------------------------------------------------------

class mujoco_msg_mj_tend : public ::google::protobuf::Message {
 public:
  mujoco_msg_mj_tend();
  virtual ~mujoco_msg_mj_tend();

  mujoco_msg_mj_tend(const mujoco_msg_mj_tend& from);

  inline mujoco_msg_mj_tend& operator=(const mujoco_msg_mj_tend& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const mujoco_msg_mj_tend& default_instance();

  void Swap(mujoco_msg_mj_tend* other);

  // implements Message ----------------------------------------------

  inline mujoco_msg_mj_tend* New() const { return New(NULL); }

  mujoco_msg_mj_tend* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mujoco_msg_mj_tend& from);
  void MergeFrom(const mujoco_msg_mj_tend& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(mujoco_msg_mj_tend* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional double len = 2;
  void clear_len();
  static const int kLenFieldNumber = 2;
  double len() const;
  void set_len(double value);

  // optional double len0 = 3;
  void clear_len0();
  static const int kLen0FieldNumber = 3;
  double len0() const;
  void set_len0(double value);

  // optional double len_dot = 4;
  void clear_len_dot();
  static const int kLenDotFieldNumber = 4;
  double len_dot() const;
  void set_len_dot(double value);

  // optional double ma = 5;
  void clear_ma();
  static const int kMaFieldNumber = 5;
  double ma() const;
  void set_ma(double value);

  // @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_tend)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  double len_;
  double len0_;
  double len_dot_;
  double ma_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_mujoco2py_2eproto();
  friend void protobuf_AssignDesc_mujoco2py_2eproto();
  friend void protobuf_ShutdownFile_mujoco2py_2eproto();

  void InitAsDefaultInstance();
  static mujoco_msg_mj_tend* default_instance_;
};
// -------------------------------------------------------------------

class mujoco_msg_mj_site : public ::google::protobuf::Message {
 public:
  mujoco_msg_mj_site();
  virtual ~mujoco_msg_mj_site();

  mujoco_msg_mj_site(const mujoco_msg_mj_site& from);

  inline mujoco_msg_mj_site& operator=(const mujoco_msg_mj_site& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const mujoco_msg_mj_site& default_instance();

  void Swap(mujoco_msg_mj_site* other);

  // implements Message ----------------------------------------------

  inline mujoco_msg_mj_site* New() const { return New(NULL); }

  mujoco_msg_mj_site* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mujoco_msg_mj_site& from);
  void MergeFrom(const mujoco_msg_mj_site& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(mujoco_msg_mj_site* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional double x = 2;
  void clear_x();
  static const int kXFieldNumber = 2;
  double x() const;
  void set_x(double value);

  // optional double y = 3;
  void clear_y();
  static const int kYFieldNumber = 3;
  double y() const;
  void set_y(double value);

  // optional double z = 4;
  void clear_z();
  static const int kZFieldNumber = 4;
  double z() const;
  void set_z(double value);

  // @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg.mj_site)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  double x_;
  double y_;
  double z_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_mujoco2py_2eproto();
  friend void protobuf_AssignDesc_mujoco2py_2eproto();
  friend void protobuf_ShutdownFile_mujoco2py_2eproto();

  void InitAsDefaultInstance();
  static mujoco_msg_mj_site* default_instance_;
};
// -------------------------------------------------------------------

class mujoco_msg : public ::google::protobuf::Message {
 public:
  mujoco_msg();
  virtual ~mujoco_msg();

  mujoco_msg(const mujoco_msg& from);

  inline mujoco_msg& operator=(const mujoco_msg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const mujoco_msg& default_instance();

  void Swap(mujoco_msg* other);

  // implements Message ----------------------------------------------

  inline mujoco_msg* New() const { return New(NULL); }

  mujoco_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mujoco_msg& from);
  void MergeFrom(const mujoco_msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(mujoco_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef mujoco_msg_mj_joint mj_joint;
  typedef mujoco_msg_mj_act mj_act;
  typedef mujoco_msg_mj_tend mj_tend;
  typedef mujoco_msg_mj_site mj_site;

  // accessors -------------------------------------------------------

  // repeated .mujoco2py.mujoco_msg.mj_joint joint = 1;
  int joint_size() const;
  void clear_joint();
  static const int kJointFieldNumber = 1;
  const ::mujoco2py::mujoco_msg_mj_joint& joint(int index) const;
  ::mujoco2py::mujoco_msg_mj_joint* mutable_joint(int index);
  ::mujoco2py::mujoco_msg_mj_joint* add_joint();
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_joint >*
      mutable_joint();
  const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_joint >&
      joint() const;

  // repeated .mujoco2py.mujoco_msg.mj_act act = 2;
  int act_size() const;
  void clear_act();
  static const int kActFieldNumber = 2;
  const ::mujoco2py::mujoco_msg_mj_act& act(int index) const;
  ::mujoco2py::mujoco_msg_mj_act* mutable_act(int index);
  ::mujoco2py::mujoco_msg_mj_act* add_act();
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_act >*
      mutable_act();
  const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_act >&
      act() const;

  // repeated .mujoco2py.mujoco_msg.mj_tend tend = 3;
  int tend_size() const;
  void clear_tend();
  static const int kTendFieldNumber = 3;
  const ::mujoco2py::mujoco_msg_mj_tend& tend(int index) const;
  ::mujoco2py::mujoco_msg_mj_tend* mutable_tend(int index);
  ::mujoco2py::mujoco_msg_mj_tend* add_tend();
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_tend >*
      mutable_tend();
  const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_tend >&
      tend() const;

  // repeated .mujoco2py.mujoco_msg.mj_site site = 4;
  int site_size() const;
  void clear_site();
  static const int kSiteFieldNumber = 4;
  const ::mujoco2py::mujoco_msg_mj_site& site(int index) const;
  ::mujoco2py::mujoco_msg_mj_site* mutable_site(int index);
  ::mujoco2py::mujoco_msg_mj_site* add_site();
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_site >*
      mutable_site();
  const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_site >&
      site() const;

  // @@protoc_insertion_point(class_scope:mujoco2py.mujoco_msg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_joint > joint_;
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_act > act_;
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_tend > tend_;
  ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_site > site_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_mujoco2py_2eproto();
  friend void protobuf_AssignDesc_mujoco2py_2eproto();
  friend void protobuf_ShutdownFile_mujoco2py_2eproto();

  void InitAsDefaultInstance();
  static mujoco_msg* default_instance_;
};
// -------------------------------------------------------------------

class general_msg : public ::google::protobuf::Message {
 public:
  general_msg();
  virtual ~general_msg();

  general_msg(const general_msg& from);

  inline general_msg& operator=(const general_msg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const general_msg& default_instance();

  void Swap(general_msg* other);

  // implements Message ----------------------------------------------

  inline general_msg* New() const { return New(NULL); }

  general_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const general_msg& from);
  void MergeFrom(const general_msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(general_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string instruction = 1;
  void clear_instruction();
  static const int kInstructionFieldNumber = 1;
  const ::std::string& instruction() const;
  void set_instruction(const ::std::string& value);
  void set_instruction(const char* value);
  void set_instruction(const char* value, size_t size);
  ::std::string* mutable_instruction();
  ::std::string* release_instruction();
  void set_allocated_instruction(::std::string* instruction);

  // repeated double value = 2;
  int value_size() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  double value(int index) const;
  void set_value(int index, double value);
  void add_value(double value);
  const ::google::protobuf::RepeatedField< double >&
      value() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_value();

  // @@protoc_insertion_point(class_scope:mujoco2py.general_msg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr instruction_;
  ::google::protobuf::RepeatedField< double > value_;
  mutable int _value_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_mujoco2py_2eproto();
  friend void protobuf_AssignDesc_mujoco2py_2eproto();
  friend void protobuf_ShutdownFile_mujoco2py_2eproto();

  void InitAsDefaultInstance();
  static general_msg* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// mujoco_msg_mj_joint

// optional string name = 1;
inline void mujoco_msg_mj_joint::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& mujoco_msg_mj_joint::name() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_joint.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_joint::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_joint.name)
}
inline void mujoco_msg_mj_joint::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mujoco2py.mujoco_msg.mj_joint.name)
}
inline void mujoco_msg_mj_joint::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mujoco2py.mujoco_msg.mj_joint.name)
}
inline ::std::string* mujoco_msg_mj_joint::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.mj_joint.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* mujoco_msg_mj_joint::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_joint::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mujoco2py.mujoco_msg.mj_joint.name)
}

// optional double qpos = 2;
inline void mujoco_msg_mj_joint::clear_qpos() {
  qpos_ = 0;
}
inline double mujoco_msg_mj_joint::qpos() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_joint.qpos)
  return qpos_;
}
inline void mujoco_msg_mj_joint::set_qpos(double value) {
  
  qpos_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_joint.qpos)
}

// optional double force = 3;
inline void mujoco_msg_mj_joint::clear_force() {
  force_ = 0;
}
inline double mujoco_msg_mj_joint::force() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_joint.force)
  return force_;
}
inline void mujoco_msg_mj_joint::set_force(double value) {
  
  force_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_joint.force)
}

// -------------------------------------------------------------------

// mujoco_msg_mj_act

// optional double ctrl = 1;
inline void mujoco_msg_mj_act::clear_ctrl() {
  ctrl_ = 0;
}
inline double mujoco_msg_mj_act::ctrl() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_act.ctrl)
  return ctrl_;
}
inline void mujoco_msg_mj_act::set_ctrl(double value) {
  
  ctrl_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_act.ctrl)
}

// optional string name = 2;
inline void mujoco_msg_mj_act::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& mujoco_msg_mj_act::name() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_act.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_act::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_act.name)
}
inline void mujoco_msg_mj_act::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mujoco2py.mujoco_msg.mj_act.name)
}
inline void mujoco_msg_mj_act::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mujoco2py.mujoco_msg.mj_act.name)
}
inline ::std::string* mujoco_msg_mj_act::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.mj_act.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* mujoco_msg_mj_act::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_act::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mujoco2py.mujoco_msg.mj_act.name)
}

// optional double force = 3;
inline void mujoco_msg_mj_act::clear_force() {
  force_ = 0;
}
inline double mujoco_msg_mj_act::force() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_act.force)
  return force_;
}
inline void mujoco_msg_mj_act::set_force(double value) {
  
  force_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_act.force)
}

// -------------------------------------------------------------------

// mujoco_msg_mj_tend

// optional string name = 1;
inline void mujoco_msg_mj_tend::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& mujoco_msg_mj_tend::name() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_tend.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_tend::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_tend.name)
}
inline void mujoco_msg_mj_tend::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mujoco2py.mujoco_msg.mj_tend.name)
}
inline void mujoco_msg_mj_tend::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mujoco2py.mujoco_msg.mj_tend.name)
}
inline ::std::string* mujoco_msg_mj_tend::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.mj_tend.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* mujoco_msg_mj_tend::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_tend::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mujoco2py.mujoco_msg.mj_tend.name)
}

// optional double len = 2;
inline void mujoco_msg_mj_tend::clear_len() {
  len_ = 0;
}
inline double mujoco_msg_mj_tend::len() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_tend.len)
  return len_;
}
inline void mujoco_msg_mj_tend::set_len(double value) {
  
  len_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_tend.len)
}

// optional double len0 = 3;
inline void mujoco_msg_mj_tend::clear_len0() {
  len0_ = 0;
}
inline double mujoco_msg_mj_tend::len0() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_tend.len0)
  return len0_;
}
inline void mujoco_msg_mj_tend::set_len0(double value) {
  
  len0_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_tend.len0)
}

// optional double len_dot = 4;
inline void mujoco_msg_mj_tend::clear_len_dot() {
  len_dot_ = 0;
}
inline double mujoco_msg_mj_tend::len_dot() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_tend.len_dot)
  return len_dot_;
}
inline void mujoco_msg_mj_tend::set_len_dot(double value) {
  
  len_dot_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_tend.len_dot)
}

// optional double ma = 5;
inline void mujoco_msg_mj_tend::clear_ma() {
  ma_ = 0;
}
inline double mujoco_msg_mj_tend::ma() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_tend.ma)
  return ma_;
}
inline void mujoco_msg_mj_tend::set_ma(double value) {
  
  ma_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_tend.ma)
}

// -------------------------------------------------------------------

// mujoco_msg_mj_site

// optional string name = 1;
inline void mujoco_msg_mj_site::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& mujoco_msg_mj_site::name() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_site.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_site::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_site.name)
}
inline void mujoco_msg_mj_site::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mujoco2py.mujoco_msg.mj_site.name)
}
inline void mujoco_msg_mj_site::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mujoco2py.mujoco_msg.mj_site.name)
}
inline ::std::string* mujoco_msg_mj_site::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.mj_site.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* mujoco_msg_mj_site::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mujoco_msg_mj_site::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mujoco2py.mujoco_msg.mj_site.name)
}

// optional double x = 2;
inline void mujoco_msg_mj_site::clear_x() {
  x_ = 0;
}
inline double mujoco_msg_mj_site::x() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_site.x)
  return x_;
}
inline void mujoco_msg_mj_site::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_site.x)
}

// optional double y = 3;
inline void mujoco_msg_mj_site::clear_y() {
  y_ = 0;
}
inline double mujoco_msg_mj_site::y() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_site.y)
  return y_;
}
inline void mujoco_msg_mj_site::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_site.y)
}

// optional double z = 4;
inline void mujoco_msg_mj_site::clear_z() {
  z_ = 0;
}
inline double mujoco_msg_mj_site::z() const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.mj_site.z)
  return z_;
}
inline void mujoco_msg_mj_site::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:mujoco2py.mujoco_msg.mj_site.z)
}

// -------------------------------------------------------------------

// mujoco_msg

// repeated .mujoco2py.mujoco_msg.mj_joint joint = 1;
inline int mujoco_msg::joint_size() const {
  return joint_.size();
}
inline void mujoco_msg::clear_joint() {
  joint_.Clear();
}
inline const ::mujoco2py::mujoco_msg_mj_joint& mujoco_msg::joint(int index) const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.joint)
  return joint_.Get(index);
}
inline ::mujoco2py::mujoco_msg_mj_joint* mujoco_msg::mutable_joint(int index) {
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.joint)
  return joint_.Mutable(index);
}
inline ::mujoco2py::mujoco_msg_mj_joint* mujoco_msg::add_joint() {
  // @@protoc_insertion_point(field_add:mujoco2py.mujoco_msg.joint)
  return joint_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_joint >*
mujoco_msg::mutable_joint() {
  // @@protoc_insertion_point(field_mutable_list:mujoco2py.mujoco_msg.joint)
  return &joint_;
}
inline const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_joint >&
mujoco_msg::joint() const {
  // @@protoc_insertion_point(field_list:mujoco2py.mujoco_msg.joint)
  return joint_;
}

// repeated .mujoco2py.mujoco_msg.mj_act act = 2;
inline int mujoco_msg::act_size() const {
  return act_.size();
}
inline void mujoco_msg::clear_act() {
  act_.Clear();
}
inline const ::mujoco2py::mujoco_msg_mj_act& mujoco_msg::act(int index) const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.act)
  return act_.Get(index);
}
inline ::mujoco2py::mujoco_msg_mj_act* mujoco_msg::mutable_act(int index) {
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.act)
  return act_.Mutable(index);
}
inline ::mujoco2py::mujoco_msg_mj_act* mujoco_msg::add_act() {
  // @@protoc_insertion_point(field_add:mujoco2py.mujoco_msg.act)
  return act_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_act >*
mujoco_msg::mutable_act() {
  // @@protoc_insertion_point(field_mutable_list:mujoco2py.mujoco_msg.act)
  return &act_;
}
inline const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_act >&
mujoco_msg::act() const {
  // @@protoc_insertion_point(field_list:mujoco2py.mujoco_msg.act)
  return act_;
}

// repeated .mujoco2py.mujoco_msg.mj_tend tend = 3;
inline int mujoco_msg::tend_size() const {
  return tend_.size();
}
inline void mujoco_msg::clear_tend() {
  tend_.Clear();
}
inline const ::mujoco2py::mujoco_msg_mj_tend& mujoco_msg::tend(int index) const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.tend)
  return tend_.Get(index);
}
inline ::mujoco2py::mujoco_msg_mj_tend* mujoco_msg::mutable_tend(int index) {
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.tend)
  return tend_.Mutable(index);
}
inline ::mujoco2py::mujoco_msg_mj_tend* mujoco_msg::add_tend() {
  // @@protoc_insertion_point(field_add:mujoco2py.mujoco_msg.tend)
  return tend_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_tend >*
mujoco_msg::mutable_tend() {
  // @@protoc_insertion_point(field_mutable_list:mujoco2py.mujoco_msg.tend)
  return &tend_;
}
inline const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_tend >&
mujoco_msg::tend() const {
  // @@protoc_insertion_point(field_list:mujoco2py.mujoco_msg.tend)
  return tend_;
}

// repeated .mujoco2py.mujoco_msg.mj_site site = 4;
inline int mujoco_msg::site_size() const {
  return site_.size();
}
inline void mujoco_msg::clear_site() {
  site_.Clear();
}
inline const ::mujoco2py::mujoco_msg_mj_site& mujoco_msg::site(int index) const {
  // @@protoc_insertion_point(field_get:mujoco2py.mujoco_msg.site)
  return site_.Get(index);
}
inline ::mujoco2py::mujoco_msg_mj_site* mujoco_msg::mutable_site(int index) {
  // @@protoc_insertion_point(field_mutable:mujoco2py.mujoco_msg.site)
  return site_.Mutable(index);
}
inline ::mujoco2py::mujoco_msg_mj_site* mujoco_msg::add_site() {
  // @@protoc_insertion_point(field_add:mujoco2py.mujoco_msg.site)
  return site_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_site >*
mujoco_msg::mutable_site() {
  // @@protoc_insertion_point(field_mutable_list:mujoco2py.mujoco_msg.site)
  return &site_;
}
inline const ::google::protobuf::RepeatedPtrField< ::mujoco2py::mujoco_msg_mj_site >&
mujoco_msg::site() const {
  // @@protoc_insertion_point(field_list:mujoco2py.mujoco_msg.site)
  return site_;
}

// -------------------------------------------------------------------

// general_msg

// optional string instruction = 1;
inline void general_msg::clear_instruction() {
  instruction_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& general_msg::instruction() const {
  // @@protoc_insertion_point(field_get:mujoco2py.general_msg.instruction)
  return instruction_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void general_msg::set_instruction(const ::std::string& value) {
  
  instruction_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mujoco2py.general_msg.instruction)
}
inline void general_msg::set_instruction(const char* value) {
  
  instruction_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mujoco2py.general_msg.instruction)
}
inline void general_msg::set_instruction(const char* value, size_t size) {
  
  instruction_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mujoco2py.general_msg.instruction)
}
inline ::std::string* general_msg::mutable_instruction() {
  
  // @@protoc_insertion_point(field_mutable:mujoco2py.general_msg.instruction)
  return instruction_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* general_msg::release_instruction() {
  
  return instruction_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void general_msg::set_allocated_instruction(::std::string* instruction) {
  if (instruction != NULL) {
    
  } else {
    
  }
  instruction_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), instruction);
  // @@protoc_insertion_point(field_set_allocated:mujoco2py.general_msg.instruction)
}

// repeated double value = 2;
inline int general_msg::value_size() const {
  return value_.size();
}
inline void general_msg::clear_value() {
  value_.Clear();
}
inline double general_msg::value(int index) const {
  // @@protoc_insertion_point(field_get:mujoco2py.general_msg.value)
  return value_.Get(index);
}
inline void general_msg::set_value(int index, double value) {
  value_.Set(index, value);
  // @@protoc_insertion_point(field_set:mujoco2py.general_msg.value)
}
inline void general_msg::add_value(double value) {
  value_.Add(value);
  // @@protoc_insertion_point(field_add:mujoco2py.general_msg.value)
}
inline const ::google::protobuf::RepeatedField< double >&
general_msg::value() const {
  // @@protoc_insertion_point(field_list:mujoco2py.general_msg.value)
  return value_;
}
inline ::google::protobuf::RepeatedField< double >*
general_msg::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:mujoco2py.general_msg.value)
  return &value_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mujoco2py

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mujoco2py_2eproto__INCLUDED
